name: Conversion Request
description: Request to convert a Java pack to Bedrock
labels: ["conversion"]
body:
  - type: input
    id: java-pack-direct-download-url
    attributes:
      label: Java Pack Direct Download URL
      description: Provide a direct download link to the Java resource pack (e.g., from Google Drive, Dropbox)
      placeholder: https://example.com/pack.zip
    validations:
      required: true
  - type: input
    id: default-pack-direct-download-url
    attributes:
      label: Default Pack Direct Download URL (Optional)
      description: Direct link to a default Bedrock pack (leave blank if not needed)
      placeholder: https://example.com/default_pack.zip
  - type: input
    id: bedrock-merge-pack-direct-download-url
    attributes:
      label: Bedrock Merge Pack Direct Download URL (Optional)
      description: Direct link to a Bedrock pack to merge with
      placeholder: https://example.com/merge_pack.zip
  - type: input
    id: default-assets-version
    attributes:
      label: Default Assets Version (Optional)
      description: Minecraft version for default assets (e.g., 1.19.3)
      placeholder: 1.19.3
  - type: input
    id: block-material
    attributes:
      label: Block Material (Optional)
      description: Material for blocks (default: alpha_test)
      placeholder: alpha_test
  - type: input
    id: attachable-material
    attributes:
      label: Attachable Material (Optional)
      description: Material for attachables (default: entity_alphatest_one_sided)
      placeholder: entity_alphatest_one_sided
  - type: dropdown
    id: archive-scratch-files
    attributes:
      label: Archive Scratch Files?
      description: Archive temporary files? (true/false)
      options:
        - "false"
        - "true"
      default: 0
  - type: dropdown
    id: rename-model-files
    attributes:
      label: Rename Model Files?
      description: Rename model files during conversion? (true/false)
      options:
        - "false"
        - "true"
      default: 0
